# Generated by Django 2.2.6 on 2019-10-11 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('med_store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='qty',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
