# Generated by Django 2.2.6 on 2019-10-15 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('med_store', '0002_operation_qty'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='price',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='document',
            name='attachment',
            field=models.FileField(upload_to='documents/%Y/%m/%d/user/'),
        ),
    ]
