# Generated by Django 2.2.6 on 2019-10-15 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('med_store', '0003_auto_20191015_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='doc_type',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
