# Generated by Django 2.2.6 on 2019-10-16 09:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('med_store', '0004_auto_20191015_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='attachment',
            field=models.FileField(upload_to='documents/%Y/%m/%d/user/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['xlsx', 'xls'])]),
        ),
    ]
