# Generated by Django 2.2.6 on 2019-10-17 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('med_store', '0008_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='end_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='report',
            name='start_date',
            field=models.DateTimeField(),
        ),
    ]
